export const locations = [
  { label: "Thủ Đức", value: "Thành phố Thủ Đức" },
  { label: "Bình Thạnh", value: "Quận Bình Thạnh" },
  { label: "Gò Vấp", value: "Quận Gò Vấp" },
  { label: "Quận 3", value: "Quận 3" },
  { label: "Quận 5", value: "Quận 5" },
  { label: "Quận 10", value: "Quận 10" },
  { label: "Quận 1", value: "Quận 1" },
  { label: "Quận 4", value: "Quận 4" },
  { label: "Quận 6", value: "Quận 6" },
  { label: "Quận 7", value: "Quận 7" },
  { label: "Quận 8", value: "Quận 8" },
  { label: "Quận 11", value: "Quận 11" },
  { label: "Quận 12", value: "Quận 12" },
  { label: "Bình Tân", value: "Quận Bình Tân" },
  { label: "Phú Nhuận", value: "Quận Phú Nhuận" },
  { label: "Tân Bình", value: "Quận Tân Bình" },
  { label: "Tân Phú", value: "Quận Tân Phú" },
  { label: "Bình Chánh", value: "Quận Bình Chánh" },
  { label: "Cần Giờ", value: "Cần Giờ" },
  { label: "Củ Chi", value: "Củ Chi" },
  { label: "Hóc Môn", value: "Hóc Môn" },
  { label: "Nhà Bè", value: "Nhà Bè" },
];
